'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ember_Media_Manager_WPF.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property actor_silhouette() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actor_silhouette", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property asc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnCancel_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearFilters_Movies_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearFilters_Movies_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearFilters_MovieSets_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearFilters_MovieSets_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearFilters_Shows_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearFilters_Shows_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnMarkAll_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMarkAll_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnUnmarkAll_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnUnmarkAll_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeChange_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeChange_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeEdit_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeEdit_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeLock_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeLock_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeMark_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeMark_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeOpenFolder_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeOpenFolder_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeReload_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeReload_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeRemove_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeRemove_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeRemoveFromDB_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeRemoveFromDB_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeRemoveFromDisk_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeRemoveFromDisk_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeScrape_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeScrape_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeScrapeSelected_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeScrapeSelected_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeTitle_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeTitle_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeUnlock_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeUnlock_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuEpisodeUnmarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuEpisodeUnmarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieChangeAutoImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieChangeAutoImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieChangeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieChangeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieEditImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieEditImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieEditMetaDataImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieEditMetaDataImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieLockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieLockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieMarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieMarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieOpenFolderImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieOpenFolderImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieReloadImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieReloadImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieRemoveFromDBImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieRemoveFromDBImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieRemoveFromDiskImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieRemoveFromDiskImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieRemoveImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieRemoveImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieScrapeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieScrapeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieScrapeSelectedImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieScrapeSelectedImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetEditImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetEditImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetLockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetLockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetMarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetMarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetReloadImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetReloadImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetRemoveImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetRemoveImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetScrapeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetScrapeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetScrapeSelectedImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetScrapeSelectedImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetTitleImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetTitleImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetUnlockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetUnlockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieSetUnmarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieSetUnmarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieTitleImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieTitleImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieUnlockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieUnlockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuMovieUnmarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuMovieUnmarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonEditImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonEditImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonLockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonLockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonMarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonMarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonOpenFolderImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonOpenFolderImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonReloadFullImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonReloadFullImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonReloadImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonReloadImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonRemoveFromDBImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonRemoveFromDBImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonRemoveFromDiskImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonRemoveFromDiskImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonRemoveImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonRemoveImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonScrapeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonScrapeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonScrapeSelectedImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonScrapeSelectedImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonTitleImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonTitleImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonUnlockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonUnlockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuSeasonUnmarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuSeasonUnmarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowChangeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowChangeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowClearCacheImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowClearCacheImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowEditImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowEditImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowLockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowLockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowMarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowMarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowOpenFolderImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowOpenFolderImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowReloadFullImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowReloadFullImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowReloadImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowReloadImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowRemoveFromDBImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowRemoveFromDBImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowRemoveFromDiskImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowRemoveFromDiskImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowRemoveImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowRemoveImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowScrapeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowScrapeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowScrapeSelectedImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowScrapeSelectedImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowTitleImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowTitleImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowUnlockImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowUnlockImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuShowUnmarkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuShowUnmarkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayExitImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayExitImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayScrapeMovieSetsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayScrapeMovieSetsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayScrapeMoviesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayScrapeMoviesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayScrapeTVShowsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayScrapeTVShowsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTraySettingsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTraySettingsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayTitleImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayTitleImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsBackdropImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsBackdropImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsCleanDBImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsCleanDBImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsCleanFilesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsCleanFilesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsClearCacheImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsClearCacheImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsOfflineHolderImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsOfflineHolderImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsReloadMovieSetsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsReloadMovieSetsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsReloadMoviesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsReloadMoviesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsReloadTVShowsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsReloadTVShowsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayToolsSortFilesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayToolsSortFilesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmnuTrayUpdateImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmnuTrayUpdateImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property de() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("de", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property doRating() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doRating", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmberSplashScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmberSplashScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property General() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("General", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasActorThumb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasActorThumb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasBanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasBanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasCharacterArt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasCharacterArt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasClearArt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasClearArt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasClearLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasClearLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasDiscArt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasDiscArt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasExtrafanart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasExtrafanart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasExtrathumb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasExtrathumb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasFanart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasFanart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasLandscape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasLandscape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasLanguage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasLanguage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasMeta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasMeta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasNfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasNfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasPoster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasPoster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasSet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasSet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasSubtitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasSubtitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasTheme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasTheme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasTrailer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasTrailer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property haswatched() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("haswatched", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invalid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invalid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        '''&lt;Languages&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Dansk&lt;/name&gt;
        '''    &lt;abbreviation&gt;da&lt;/abbreviation&gt;
        '''    &lt;id&gt;10&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Suomeksi&lt;/name&gt;
        '''    &lt;abbreviation&gt;fi&lt;/abbreviation&gt;
        '''    &lt;id&gt;11&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Nederlands&lt;/name&gt;
        '''    &lt;abbreviation&gt;nl&lt;/abbreviation&gt;
        '''    &lt;id&gt;13&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Deutsch&lt;/name&gt;
        '''    &lt;abbreviation&gt;de&lt;/abbreviation&gt;
        '''    &lt;id&gt;14&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Italiano&lt;/name&gt;
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property languages() As String
            Get
                Return ResourceManager.GetString("languages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;center&gt;&lt;b&gt;Movie List&lt;/b&gt;&lt;/center&gt;&lt;/br&gt;.
        '''</summary>
        Friend ReadOnly Property MediaListLogo() As String
            Get
                Return ResourceManager.GetString("MediaListLogo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menuAdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuAdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Miscellaneous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Miscellaneous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainDonateImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainDonateImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainEditSettingsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainEditSettingsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainErrorImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainErrorImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainFileExitImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainFileExitImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainHelpAboutImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainHelpAboutImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainHelpUpdateImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainHelpUpdateImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainHelpVersionsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainHelpVersionsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainHelpWikiImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainHelpWikiImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsBackdropsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsBackdropsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsCleanDBImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsCleanDBImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsCleanFilesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsCleanFilesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsClearCacheImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsClearCacheImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsOfflineHolderImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsOfflineHolderImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsReloadMovieSetsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsReloadMovieSetsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsReloadMoviesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsReloadMoviesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsReloadTVShowsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsReloadTVShowsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsRewriteMovieContentImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsRewriteMovieContentImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuMainToolsSortFilesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuMainToolsSortFilesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuScrapeMovieSetsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuScrapeMovieSetsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuScrapeMoviesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuScrapeMoviesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuScrapeTVShowsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuScrapeTVShowsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mnuUpdateImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mnuUpdateImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modules() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modules", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Movie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Movie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/system.drawing.knowncol [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property movie_Default() As String
            Get
                Return ResourceManager.GetString("movie_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property MovieListFooter() As String
            Get
                Return ResourceManager.GetString("MovieListFooter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;style type=&quot;text/css&quot;&gt;
        '''&lt;!--
        '''body {background: #FFFFFF; /* The background of the page will be colored white */}
        '''a:link {color: #000000; /* All unvisited links will be colored black */ }
        '''a:visited {color: #FF9900; /* All visited links will be colored tan */ }
        '''a:active {color: #FF0000; /* All active links will be colored red */}
        '''a:hover {color: #0000FF; background: #FFFF00;}
        '''/* When the mouse pointer is over the link the link will be colored blue
        '''and the background color of the link will change  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MovieListHeader() As String
            Get
                Return ResourceManager.GetString("MovieListHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;td&gt;&lt;span style=&quot;color:darkblue;&quot;&gt;{0}&lt;/span&gt;&lt;/td&gt;.
        '''</summary>
        Friend ReadOnly Property MovieListTableCol() As String
            Get
                Return ResourceManager.GetString("MovieListTableCol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/table&gt;
        '''&lt;/center&gt;.
        '''</summary>
        Friend ReadOnly Property MovieListTableEnd() As String
            Get
                Return ResourceManager.GetString("MovieListTableEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;th style=&quot;text-align:left; &quot;&gt;{0}&lt;/th&gt;.
        '''</summary>
        Friend ReadOnly Property MovieListTableHeader() As String
            Get
                Return ResourceManager.GetString("MovieListTableHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/tr&gt;.
        '''</summary>
        Friend ReadOnly Property MovieListTableRowEnd() As String
            Get
                Return ResourceManager.GetString("MovieListTableRowEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;tr&gt;.
        '''</summary>
        Friend ReadOnly Property MovieListTableRowStart() As String
            Get
                Return ResourceManager.GetString("MovieListTableRowStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;center&gt;
        '''&lt;table class=&quot;emm_table&quot;&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property MovieListTableStart() As String
            Get
                Return ResourceManager.GetString("MovieListTableStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MovieSet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MovieSet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/system.drawing.knowncol [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property movieset_Default() As String
            Get
                Return ResourceManager.GetString("movieset_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property msaa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msaa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noposter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noposter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pbActLoadImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pbActLoadImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pbLoadSettingsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pbLoadSettingsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pbMILoadingImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pbMILoadingImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pbNoInfoImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pbNoInfoImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pbTop250Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pbTop250Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picSearchMovieSetsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picSearchMovieSetsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picSearchMoviesImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picSearchMoviesImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picSearchTVShowsImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picSearchTVShowsImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puzzle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puzzle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property starempty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starempty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property starhalf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starhalf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tmdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tmdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tvdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/system.drawing.knowncol [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property tvep_Default() As String
            Get
                Return ResourceManager.GetString("tvep_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/system.drawing.knowncol [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property tvshow_Default() As String
            Get
                Return ResourceManager.GetString("tvshow_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TVShows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TVShows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tvtunes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvtunes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.EmberMediaManager.org/.
        '''</summary>
        Friend ReadOnly Property urlEmberMediaManager() As String
            Get
                Return ResourceManager.GetString("urlEmberMediaManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://wiki.embermediamanager.org.
        '''</summary>
        Friend ReadOnly Property urlEmberWiki() As String
            Get
                Return ResourceManager.GetString("urlEmberWiki", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.ffmpeg.org/.
        '''</summary>
        Friend ReadOnly Property urlFfmpeg() As String
            Get
                Return ResourceManager.GetString("urlFfmpeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://forum.kodi.tv/forumdisplay.php?fid=195.
        '''</summary>
        Friend ReadOnly Property urlForumEng() As String
            Get
                Return ResourceManager.GetString("urlForumEng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.kodinerds.net/index.php/Board/105-Ember-Media-Manager/.
        '''</summary>
        Friend ReadOnly Property urlForumGer() As String
            Get
                Return ResourceManager.GetString("urlForumGer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.imdb.com/.
        '''</summary>
        Friend ReadOnly Property urlIMDB() As String
            Get
                Return ResourceManager.GetString("urlIMDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.impawards.com/.
        '''</summary>
        Friend ReadOnly Property urlIMPAwards() As String
            Get
                Return ResourceManager.GetString("urlIMPAwards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://mediainfo.sourceforge.net.
        '''</summary>
        Friend ReadOnly Property urlMediaInfo() As String
            Get
                Return ResourceManager.GetString("urlMediaInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.moviepostersdb.com/.
        '''</summary>
        Friend ReadOnly Property urlMoviePostersDb() As String
            Get
                Return ResourceManager.GetString("urlMoviePostersDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://forum.kodi.tv/showthread.php?tid=259449.
        '''</summary>
        Friend ReadOnly Property urlReleaseThread() As String
            Get
                Return ResourceManager.GetString("urlReleaseThread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.themoviedb.org/.
        '''</summary>
        Friend ReadOnly Property urlTheMovieDb() As String
            Get
                Return ResourceManager.GetString("urlTheMovieDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://thetvdb.com/.
        '''</summary>
        Friend ReadOnly Property urlTVDB() As String
            Get
                Return ResourceManager.GetString("urlTVDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.xbmc.org/.
        '''</summary>
        Friend ReadOnly Property urlXBMC() As String
            Get
                Return ResourceManager.GetString("urlXBMC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.youtube.com/.
        '''</summary>
        Friend ReadOnly Property urlYouTube() As String
            Get
                Return ResourceManager.GetString("urlYouTube", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valid2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valid2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
		
		        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon.
        '''</summary>
        Friend ReadOnly Property EmmIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("EmmIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
